import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const classesName = inter.className + " size-full";
  return (
    <html lang="en" className="size-full">
      <body suppressHydrationWarning={true} className={classesName}>
        {children}
      </body>
    </html>
  );
}
