import { Inter } from "next/font/google";
import type { Metadata } from "next";

import '@fontsource/roboto/400.css';
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from 'next-intl/server';

// import '@fontsource/roboto/300.css';
// import '@fontsource/roboto/500.css';
// import '@fontsource/roboto/700.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const classesName = inter.className;
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>
      <body suppressHydrationWarning={true} className={classesName}>
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
