import { Inter } from "next/font/google";
import { PrimeReactProvider } from "primereact/api";
import type { Metadata } from "next";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const value = {
    ripple: true,
  };
  const classesName = inter.className;
  return (
    <html lang={locale}>
      <PrimeReactProvider value={value}>
        <head>
          <link
            id="theme-link"
            rel="stylesheet"
            href="/themes/lara-light-blue/theme.css"
          ></link>
        </head>
        <body suppressHydrationWarning={true} className={classesName}>
          {children}
        </body>
      </PrimeReactProvider>
    </html>
  );
}
